:memo:  Update Gene_expression_regression.ipynb
"from tensorflow import keras\n",  instead of   "import keras\n"

to avoid 
                AttributeError: module 'keras.optimizers' has no attribute 'Adam'
When compiling the Model